<?php

$sport_clubs = [
    $impuls = [
        [
            'name' => 'impuls',
            'city' => 'vilnius',
            'location' => 'trinapolio_g',
            'price_month' => 35,
            'free trial' => 'yes',
            'drinking_water' => 'yes',
            'vending_machine' => 'yes',
            'ping_pong' => 'yes',
            'wi-fi' => 'yes',
            'food' => 'yes',
            'spa' => 'no',
            'group_workouts' => 'yes',
            'swimming_pool' => 'yes',
        ],
        [
            'name' => 'impuls',
            'city' => 'vilnius',
            'location' => 'savanoriu_pr',
            'price_month' => 30,
            'free trial' => 'yes',
            'drinking_water' => 'yes',
            'vending_machine' => 'yes',
            'ping_pong' => 'no',
            'wi-fi' => 'yes',
            'food' => 'no',
            'spa' => 'yes',
            'group_workouts' => 'no',
            'swimming_pool' => 'no',
        ],
        [
            'name' => 'impuls',
            'city' => 'vilnius',
            'location' => 'vienuolio_g',
            'price_month' => 35,
            'free trial' => 'yes',
            'drinking_water' => 'yes',
            'vending_machine' => 'yes',
            'ping_pong' => 'yes',
            'wi-fi' => 'yes',
            'food' => 'yes',
            'spa' => 'yes',
            'group_workouts' => 'yes',
            'swimming_pool' => 'no',
        ],
    ],
    $gym_plius = [
        [
            'name' => 'gym_plius',
            'city' => 'vilnius',
            'location' => 'zemaites_g',
            'price_month' => 15,
            'free trial' => 'yes',
            'drinking_water' => 'yes',
            'vending_machine' => 'no',
            'ping_pong' => 'no',
            'wi-fi' => 'no',
            'food' => 'no',
            'spa' => 'no',
            'group_workouts' => 'no',
            'swimming_pool' => 'no',
        ],
        [
            'name' => 'gym_plius',
            'city' => 'vilnius',
            'location' => 'kalvariju_g',
            'price_month' => 15,
            'free trial' => 'yes',
            'drinking_water' => 'yes',
            'vending_machine' => 'no',
            'ping_pong' => 'no',
            'wi-fi' => 'no',
            'food' => 'no',
            'spa' => 'no',
            'group_workouts' => 'no',
            'swimming_pool' => 'no',
        ],
        [
            'name' => 'gym_plius',
            'city' => 'vilnius',
            'location' => 'gediminor_pr',
            'price_month' => 20,
            'free trial' => 'yes',
            'drinking_water' => 'yes',
            'vending_machine' => 'no',
            'ping_pong' => 'no',
            'wi-fi' => 'no',
            'food' => 'no',
            'spa' => 'yes',
            'group_workouts' => 'yes',
            'swimming_pool' => 'no',
        ],
    ],
    $lemon_gym = [
        [
            'name' => 'lemon_gym',
            'city' => 'vilnius',
            'location' => 'antakalnis',
            'price_month' => 20,
            'free trial' => 'no',
            'drinking_water' => 'no',
            'vending_machine' => 'yes',
            'ping_pong' => 'no',
            'wi-fi' => 'yes',
            'food' => 'no',
            'spa' => 'no',
            'group_workouts' => 'yes',
            'swimming_pool' => 'no',
        ],
        [
            'name' => "lemon_gym",
            'city' => 'vilnius',
            'location' => 'pc_banginis',
            'price_month' => 20,
            'free trial' => 'no',
            'drinking_water' => 'no',
            'vending_machine' => 'yes',
            'ping_pong' => 'no',
            'wi-fi' => 'yes',
            'food' => 'no',
            'spa' => 'no',
            'group_workouts' => 'yes',
            'swimming_pool' => 'no',
        ],
        [
            'name' => 'lemon_gym',
            'city' => 'vilnius',
            'location' => 'pc_europa',
            'price_month' => 20,
            'free trial' => 'no',
            'drinking_water' => 'no',
            'vending_machine' => 'yes',
            'ping_pong' => 'no',
            'wi-fi' => 'yes',
            'food' => 'no',
            'spa' => 'no',
            'group_workouts' => 'yes',
            'swimming_pool' => 'no',
        ],
    ],
];
